### ISSUE TITLE
RE: Cheat Mode - menus.c

### ISSUE THREAD

**Issue by DasClarky** [GMH-Code/Asylum#1]
I noticed there is a cheat mode mentioned in menus.c, there is two lines mentioning the ALT keys but i am not sure how this triggers, i have tried a few things.  Any ideas?  Thanks

**Comment by GMH-Code** [comment]
Ah yes, the cheat menu!  Well done for finding it!

Back in the day, nobody seemed to know that it existed in the original game, including me!  Most people used 'relocatable modules' to cheat on the original hardware, which, in this case, were basically mini generated programs which ran in the background.  Asylum had such a module with loads of features, so nobody needed the menu.

Anyway, the cheat mode _was_ activated by simultaneously pressing both ALTs and the middle of the three Archimedes' mouse buttons whilst the menu text was being scrolled, or when it had stopped.  The menu text then scrolled up further to show how to use the cheat keys.  I can validate this _does_ work on the original hardware, but not in this port.  The problem is pressing any key at the scroll text will drop you into the menu instead, so you never have the opportunity to switch cheats on.

I never was going to fix that bit as I never thought people would want it, but since you've raised it, I'll take a look at activating it when I have a moment.

**Comment by DasClarky** [comment]
I have played this game since it came out when i  was at school, i never saw any mention of this cheat by Andy.  I was using the DoggySoft cheat modules that you're talking about.  It would be nice to have the option in a menu! Thanks

**Comment by GMH-Code** [comment]
Sorted.  Instructions are in `README.md` -- let me know what you think!

**Comment by DasClarky** [comment]
Excellent! Thanks
